project_id = "hpbkpsofyxlacnskeukv"

[functions.create-admin]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false

[functions.manage-user]
verify_jwt = false

[functions.notify-admins]
verify_jwt = false
